id: P009077
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1582
  title: ཨ་སྟུདཡ་ཨོན་ཐེ་རཏནགོཏྲབི༹བྷག ༼ཨུཏཏརཏནཏྲ༽
  author: ''
  volumes:
    abd9dd65e2cc42afae38f9a35080eca9:
      image_group_id: I1KG1585
      title: ''
      volume_number: 1
      total_pages: 458
      base_file: v001.txt
